### ISSUE TITLE
getRetrosheet(). invalid url

### ISSUE THREAD

**Issue by pssguy** [rmscriven/retrosheet#5]
From vignette

```
getRetrosheet("schedule", 1995)
Error in getRetrosheet("schedule", 1995) : 
  'http://www.retrosheet.org/schedule/1995sked.txt' is not a valid url
```

**Comment by cswingle** [comment]
FWIW, the schedule files are now at http://www.retrosheet.org/schedule/[YYYY]SKED.ZIP and unzip to [YYYY]SKED.TXT.  I imagine that would be a fairly simple thing to fix in the code.

**Comment by SergioMarreroMarrero** [comment]
Hello. I had the same error and this conversation was the only thing I found surfing on internet. As I see, this conversation was taken one year ago, and the error is not fixed yet. There is nobody updating the package? What did you do finally Andrew Clark? thank you very much

**Comment by SergioMarreroMarrero** [comment]
I will answer myself. There is a pull-request where the error is fixed: 
https://github.com/rmscriven/retrosheet/pulls

Thanks.

**Comment by agad495** [comment]
I am getting the following error:
games.2006 = getRetrosheet("game", 2006)
Error in getRetrosheet("game", 2006) : 
  'http://www.retrosheet.org/gamelogs/gl2006.zip' is not a valid url

I clicked on the links above but they don't seem to have much information as to how I could go about correcting this error. Any advice would be greatly appreciated. Thanks.

**Comment by cswingle** [comment]
@agad495 That URL works for me this morning. Maybe your internet was temporarily down or something? If you point a web browser at it, does it download the zip file?

**Comment by amazehayes** [comment]
I am still getting that 'not a valid url' error as @agad495 

The URL does download the zip file when I put it in my browser, but does not work for me in RStudio
